# config: hyper paras

device: "cpu"
epoch: 200
EVALU_EPOCH: 50

data_path: "../data/US_temp/CONTI_15x95x267.npy"

R_U: 1
a0: 1
b0: 1
v: 1
fold: 1 # number of folds(random split) and take average,min:1,max:5'
# LDS paras for each mode
kernel: "Matern_23" # GP kernel type, Matern_21 or Matern_23", assume each mode use same kernel-type at now

lengthscale_list:
  - 0.1 # lengthscale of kernel of each mode
  - 0.1
  - 0.1
variance_list:
  - 5 # var of kernel of each mode
  - 5
  - 5
noise: 1 # obvs_noise of KF, will not be used actully

DAMPING: 0.3
DAMPING_tau: 0.5
DAMPING_gamma: 0.5

THRE: 1e-4 # therethold of CEP innner iteration

CEP_UPDATE_INNNER_MODE: True # whether do CEP mag_approx + post_update innner per mode, if false, we do it seperately after go through all mode

